name: CI

on:
  push:
    branches:
      - main
      - mockito
      - hamcrest
  pull_request:
    branches:
      - main
      - mockito
      - hamcrest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Spécifie la distribution Java à utiliser

    - name: Build with Maven
      run: mvn clean package  # Compile et empaquette le projet

    - name: Run tests
      run: mvn test  # Exécute les tests
