name: CI Pipeline

on:
  push:
    branches:
      - main
      - mockito
      - hamcrest
  pull_request:
    branches:
      - main
      - mockito
      - hamcrest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' 

      - name: Build project
        run: mvn clean package

      - name: Run tests
        run: mvn test  t
